apiVersion: v1
kind: Service
metadata:
  name: postgres-slaves
spec:
  type: LoadBalancer
  selector:
    app: database_replica
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  externalIPs:
  - 172.22.0.4
