apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432       # The port exposed by the service
      targetPort: 5432
  externalIPs:
  - 172.22.0.2
