apiVersion: v1
kind: Service
metadata:
  name: graphql-service
spec:
  type: LoadBalancer
  selector:
    app: graphql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
      # nodePort: 30001
  externalIPs:
  - 172.22.0.3
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graphql-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: graphql-service
                port:
                  number: 80