services:
  job_market_db:
    container_name: job_market_db
    image: job_market_db
    ports:  
      - "5432:5432"
    environment:
      POSTGRES_DB: JobMarketDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test

    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "JobMarketDB"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - inner_network

networks:
  inner_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
